// <copyright file="CardTest.GetHashCode01.g.cs" company="Dominion Dominators">Copyright © Dominion Dominators 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Moles;
using BDSADominion.Gamestate.Card_Types.Moles;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace BDSADominion.Gamestate.Card_Types
{
    public partial class CardTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
public void GetHashCode01358()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      SCard sCard;
      int i;
      sCard = new SCard();
      i = this.GetHashCode01((Card)sCard);
      Assert.AreEqual<int>(0, i);
    }
}
    }
}
