// <copyright file="CardFactoryTest.CreateCard.g.cs" company="Dominion Dominators">Copyright © Dominion Dominators 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using BDSADominion.Gamestate.Card_Types;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace BDSADominion.Gamestate
{
    public partial class CardFactoryTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException63()
        {
            Card card;
            card = this.CreateCard(CardName.Copper);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException285()
        {
            Card card;
            card = this.CreateCard(CardName.Silver);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException753()
        {
            Card card;
            card = this.CreateCard(CardName.Gold);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException383()
        {
            Card card;
            card = this.CreateCard(CardName.Curse);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException428()
        {
            Card card;
            card = this.CreateCard(CardName.Estate);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException90()
        {
            Card card;
            card = this.CreateCard(CardName.Province);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException601()
        {
            Card card;
            card = this.CreateCard(CardName.Duchy);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException655()
        {
            Card card;
            card = this.CreateCard(CardName.Gardens);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException784()
        {
            Card card;
            card = this.CreateCard(CardName.Cellar);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException304()
        {
            Card card;
            card = this.CreateCard(CardName.Woodcutter);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException701()
        {
            Card card;
            card = this.CreateCard(CardName.Chapel);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException657()
        {
            Card card;
            card = this.CreateCard(CardName.Workshop);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException573()
        {
            Card card;
            card = this.CreateCard(CardName.Chancellor);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException425()
        {
            Card card;
            card = this.CreateCard(CardName.Feast);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException417()
        {
            Card card;
            card = this.CreateCard(CardName.Village);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException252()
        {
            Card card;
            card = this.CreateCard(CardName.Moneylender);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException25201()
        {
            Card card;
            card = this.CreateCard(CardName.Remodel);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException638()
        {
            Card card;
            card = this.CreateCard(CardName.Smithy);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException736()
        {
            Card card;
            card = this.CreateCard(CardName.Mine);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException593()
        {
            Card card;
            card = this.CreateCard(CardName.ThroneRoom);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException611()
        {
            Card card;
            card = this.CreateCard(CardName.CouncilRoom);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException374()
        {
            Card card;
            card = this.CreateCard(CardName.Bureaucrat);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException215()
        {
            Card card;
            card = this.CreateCard(CardName.Adventurer);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException640()
        {
            Card card;
            card = this.CreateCard(CardName.Militia);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException496()
        {
            Card card;
            card = this.CreateCard(CardName.Festival);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException831()
        {
            Card card;
            card = this.CreateCard(CardName.Laboratory);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException508()
        {
            Card card;
            card = this.CreateCard(CardName.Spy);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException423()
        {
            Card card;
            card = this.CreateCard(CardName.Thief);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException73601()
        {
            Card card;
            card = this.CreateCard(CardName.Library);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException186()
        {
            Card card;
            card = this.CreateCard(CardName.Witch);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException111()
        {
            Card card;
            card = this.CreateCard(CardName.Market);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException330()
        {
            Card card;
            card = this.CreateCard(CardName.Moat);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(KeyNotFoundException))]
        public void CreateCardThrowsKeyNotFoundException196()
        {
            Card card;
            card = this.CreateCard(CardName.Copper);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [PexRaisedContractException(PexExceptionState.Expected)]
        public void CreateCardThrowsContractException978()
        {
            try
            {
                Card card;
                card = this.CreateCard(CardName.Empty);
                throw
                  new AssertFailedException("expected an exception of type ContractException");
            }
            catch (Exception ex)
            {
                if (!PexContract.IsContractException(ex))
                    throw ex;
            }
        }
        [TestMethod]
        [PexGeneratedBy(typeof(CardFactoryTest))]
        [ExpectedException(typeof(NotImplementedException))]
        public void CreateCardThrowsNotImplementedException501()
        {
            Card card;
            card = this.CreateCard((CardName)34);
        }
    }
}
