// <copyright file="CardTest.Equals02.g.cs" company="Dominion Dominators">Copyright © Dominion Dominators 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using BDSADominion.Gamestate.Card_Types.Moles;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace BDSADominion.Gamestate.Card_Types
{
    public partial class CardTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
public void Equals0259601()
{
    SCard sCard;
    SCard sCard1;
    bool b;
    sCard = new SCard();
    sCard1 = new SCard();
    b = this.Equals02((Card)sCard1, (Card)sCard);
    Assert.AreEqual<bool>(true, b);
}
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
public void Equals02596()
{
    SCard sCard;
    bool b;
    sCard = new SCard();
    b = this.Equals02((Card)sCard, (Card)sCard);
    Assert.AreEqual<bool>(true, b);
}
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
public void Equals02132()
{
    SCard sCard;
    bool b;
    sCard = new SCard();
    b = this.Equals02((Card)sCard, (Card)null);
    Assert.AreEqual<bool>(false, b);
}
    }
}
