// <copyright file="PlayerTest.Constructor.g.cs" company="Dominion Dominators">Copyright © Dominion Dominators 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace BDSADominion.Gamestate
{
    public partial class PlayerTest
    {
[TestMethod]
[PexGeneratedBy(typeof(PlayerTest))]
public void Constructor338()
{
    Player player;
    player = this.Constructor(0u);
    Assert.IsNotNull((object)player);
    Assert.AreEqual<uint>(0u, player.PlayerNumber);
    Assert.IsNotNull(player.AllCards);
    Assert.IsNotNull(player.AllCards.Comparer);
    Assert.AreEqual<int>(0, player.AllCards.Count);
    Assert.IsNotNull(player.Hand);
    Assert.AreEqual<int>(0, player.Hand.Capacity);
    Assert.AreEqual<int>(0, player.Hand.Count);
    Assert.IsNotNull(player.Played);
    Assert.AreEqual<int>(0, player.Played.Capacity);
    Assert.AreEqual<int>(0, player.Played.Count);
    Assert.IsNotNull(player.TempZone);
    Assert.AreEqual<int>(0, player.TempZone.Capacity);
    Assert.AreEqual<int>(0, player.TempZone.Count);
}
    }
}
